Fix/배너수정 #141
manito42/FrontEnd pull request #142
Opened 2023-09-19 09:26 UTC by jinaji

<img width="1437" alt="image" src="https://github.com/manito42/FrontEnd/assets/101309869/ecc56df2-eadf-4a3c-85f0-55a9c76d4102">

#141 배너 수정 

- 화살표 추가
- 하단 동그라미 크기 증가 
- 배너 연결 링크 guide 페이지로 갈 수 있도록 수정 

이동 화살표도 생겼고 동그라미들 ... 작은게 더 예쁘다고 생각하는데 나중에 얘기 나눠봐여

##

이후 해당 브랜치를 dev 에 PR 요청
dev 에 Merge 할 경우 Squash merge 를 해야합니다.
이라고 적어두셔서 일단 제가 작업한 브랜치로 PR 요청했는데, 이 PR이 완료되는 시점에서 squash merge를 해야하는 게 맞을까요? 확인 한 번 부탁드릴게여~ @JuneParkCode

2023-09-19 10:32 UTC, JuneParkCode commented
@jinaji 넵 이거 approve 되고 merge 할 때 그렇게 하시면돼요!

2023-09-19 11:31 UTC, JuneParkCode commented on 42manito/src/components/Banners/TopBanner.tsx
> +import { CaretLeftOutlined, CaretRightOutlined } from "@ant-design/icons";
import는 되어있는데 사용은 안하셨네여

근데 쓰는게 나을 것 같아요. 제 환경에서는 화살표가 조금 찌그러져 보이는데, 해당 컴포넌트 사용하면 그 문제가 발생하지 않습니다.

2023-09-19 11:33 UTC, JuneParkCode commented on 42manito/src/styles/banner.css
> +.left-arrow-button {
left 랑 right 동일한 css가 적용되는 것 같은데 하나로 퉁쳐서 관리해도 될듯

2023-09-19 11:34 UTC, JuneParkCode commented on 42manito/src/styles/banner.css
> +  @apply text-xl lg:text-3xl mr-0.5;
이 친구도 마찬가지

2023-09-19 11:35 UTC, JuneParkCode reviewed
말씀하신대로 동그라미 키우니까 밸런스가 조금 안맞는 느낌이 있는 것 같네요

슬라이드 버튼도 모바일에서는 깔끔하게 떨어지는 편인데 웹에서는 애매하게 둥 떠있는 것 같기도 하고...
나머지 분들하고 디자인 정확하게 한번 더 잡고 이야기해보면 좋을듯

이외의 코멘트는 리뷰에 적어뒀습니다!

2023-09-19 11:36 UTC, JuneParkCode requested changes
몇 개 수정할만한 부분 코멘트 남겼습니다.

2023-09-19 11:37 UTC, JuneParkCode commented on 42manito/src/components/Banners/TopBanner.tsx
> +import { CaretLeftOutlined, CaretRightOutlined } from "@ant-design/icons";
-- 적용 전
<img width="639" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/b82694b1-abcf-4d2d-8eed-51eae3fdd622">


-- 적용 후
<img width="145" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/daa28014-f861-4ecc-ace6-944555f0f861">

2023-09-19 15:19 UTC, jinaji commented on 42manito/src/components/Banners/TopBanner.tsx
> +import { CaretLeftOutlined, CaretRightOutlined } from "@ant-design/icons";
이거 ... 적용해봤다가 작업한 게 더 예뻐보여서 ㅎ 적용했는데 깨져보이시나요? 문자라 안 깨질 줄 알았는데 환경따라 다른가보네여 제 환경에서는 캡쳐해주신 이미지도 잘 보입니다! 원본이 모서리가 라운드처리 되어있는 것 같아용
그렇지만? 밑에 당장 화살표가 보이는 화면이니 통일성 위해 맞추는 것도 나쁘지 않을 것 같습니다~! 요거 다른분들 의견 주시면 그거 맞춰서 작업해올게요 ~~

2023-09-19 15:20 UTC, jinaji commented on 42manito/src/styles/banner.css
> +.left-arrow-button {
요건 left right 동일한 css가 맞는데

2023-09-19 15:21 UTC, jinaji commented on 42manito/src/styles/banner.css
> +  @apply text-xl lg:text-3xl mr-0.5;
요건 마진 넣는 방향이 다릅니다! 위에 것 합쳐둘게용~

2023-09-19 15:32 UTC, obvoso commented on 42manito/src/components/Banners/TopBanner.tsx
> +import { CaretLeftOutlined, CaretRightOutlined } from "@ant-design/icons";
기존 문자인 화살표가 가로로 눌린 거 같다는거죠?? 
맥 이모티콘이면 맥 이외에 다른 환경들에서도 변수가 생길 수 있을 거 같으니 변경해도 좋을 거 같아요
ant컴포넌트랑 원이랑 align만 해주시면 좋을 거 같습니다

2023-09-19 15:33 UTC, jinaji commented on 42manito/src/styles/banner.css
> +.left-arrow-button {
얘도 left right 가 다르네여!!

2023-09-19 15:33 UTC, obvoso approved these changes

2023-09-19 15:35 UTC, obvoso commented
하단 동그라미는 전 작은게 예쁠 거 같다고 생각하지만..,,
만약 크게 갈거면 원 사이 마진만 조금 더 주면 좋을 거 같아요

2023-09-19 15:56 UTC, jinaji commented
<img width="1440" alt="image" src="https://github.com/manito42/FrontEnd/assets/101309869/c0682f35-284c-478a-a43f-c77ebceb4026">

<img width="401" alt="image" src="https://github.com/manito42/FrontEnd/assets/101309869/7cedbb70-9a9f-413e-a6b0-2b0e6f26dc5a">

- 아이콘 수정 (제 눈엔 중앙같긴 한데 믿을 수 없음 ...)
- 원 간격 수정

원은 ... 모바일에서라도 작아야한다 ... 가 제 의견인디 디자인 관한 건 모여서 이야기 나눠봐도 좋을 것 같아여

2023-09-20 01:31 UTC, JuneParkCode commented on 42manito/src/styles/banner.css
> +.left-arrow-button {
아 그러네요 오키오키

2023-09-20 01:42 UTC, JuneParkCode commented
저도 모바일에서라도 작아야한다고 생각함다.

옆에 사이드 동그라미들 크기도 PC에서 조금 작아지는게 어떨까 싶은데 이건 어떻게 보시는지?

2023-09-20 01:43 UTC, JuneParkCode approved these changes

2023-09-20 04:38 UTC, jinaji commented
> 저도 모바일에서라도 작아야한다고 생각함다.
> 
> 옆에 사이드 동그라미들 크기도 PC에서 조금 작아지는게 어떨까 싶은데 이건 어떻게 보시는지? (근데 이건 만나서 같이 바꾸는게 나을 것 같아요 ㅋㅋㅋ)

저두 만나서 바꾸는 게 나을 것 같아서!! 머지 안 시키고 있겠습니다 나중에 다같이 함 봐여 ~~

2023-09-20 04:47 UTC, JuneParkCode commented
넵! 고생 많으셨습니다!

2023-09-20 10:35 UTC, falconlee236 approved these changes
리뷰 완료했습니다
저는 사실 왼쪽 오른쪽 버튼의 크기와 가운데 정렬은 잘 맞춰진것 같은데,
모바일에서 하단 동그라미 크기 사이즈를 조금 줄이면 좋을것 같아요 모바일 화면에 비해서는 좀 큰 것 같습니다!!

2023-09-20 10:35 UTC, falconlee236 commented on 42manito/src/components/Banners/TopBanner.tsx
> +    clearTimeout(bannerTimerId);
코드를 리뷰하다가 궁금한 점이 생겼는데,
clearTimeout은 배너창이 사용자의 입력으로 인해 강제로 바뀌고 나서 다시 그 시간부터 다시 3초뒤에 배너를 바꾸기 위해서 사용한 것 맞나요?? 제가 이해한 부분이 맞는지 잘 모르겠네요

2023-09-20 14:06 UTC, jinaji commented on 42manito/src/components/Banners/TopBanner.tsx
> +    clearTimeout(bannerTimerId);
네 맞습니다! 사용자가 배너를 변경하게 되었을 때 기존 배너의 예정된 동작을 제거하지 않으면  기존 동작 + 누를 때마다 timeout 동작들이 생겨서 순서가 굉장히 꼬이더라구요
위에서 모바일 환경 말씀해주신 것까지 확인했습니다 ~~

2023-09-20 15:07 UTC, falconlee236 commented on 42manito/src/components/Banners/TopBanner.tsx
> +    clearTimeout(bannerTimerId);
답변 감사합니다!! 오늘도 하나 배워가네요

2023-09-25 07:58 UTC, merged