[todo] 멘토 활성화 시 필수 요소 확인 기능 추가
manito42/FrontEnd pull request #216
Opened 2023-09-29 13:15 UTC by falconlee236

# Summary
Profile 페이지에 있는 멘토로 활동하기 버튼을 클릭할 때 조건을 체크하는 기능을 추가했습니다.

# Description
멘토로 활동하기 버튼을 누를 때 다음과 같은 프로세스가 진행됩니다.
* 이미 버튼이 눌러져 있다면 다시 원상태로 돌아감
* 버른이 눌러져 있지 않다면 다음 조건을 체크 
1. 멘토링 분야와 관심 분야 둘다 없다면  둘다 있어야 하는 alert 출력
2. 멘토링 분야 혹은 관심분야 둘중 하나가 없다면 각각 있어야 한다는 alert 출력
3. 모두 존재한다면 그때 Toggle 상태 변화 작동

# ScreenShot
<img width="1437" alt="image" src="https://github.com/manito42/FrontEnd/assets/52999093/6e35d123-31ee-42d1-b9c5-e6fff608d196">

2023-09-30 06:25 UTC, obvoso approved these changes
세 조건 모두 alert 활성화 되는 거 확인 했습니다
감사합니다~

2023-09-30 06:27 UTC, obvoso commented on 42manito/src/components/Profile/Toggle.tsx
>    }, [userData, userLoading]);
작업하시면서 useEffect가 왜 2개인지 혹시 고려해보셨나여?
위의(첫번째) useEffect가 없어도 잘 동작할 거 같아서요

이부분은 상윤님이 추가하신게 아니지만 혹시 작업하시다가 고려하셨나 여쭤봐욤..

2023-09-30 06:33 UTC, falconlee236 commented on 42manito/src/components/Profile/Toggle.tsx
>    }, [userData, userLoading]);
제가 추가한 것은 아닌데... 한번 성준님한테 물어볼게요
@JuneParkCode

2023-09-30 07:18 UTC, JuneParkCode requested changes
작동은 확인하였고, 일부 코드 가독성 부분에서 요청드렸습니다!

2023-09-30 07:18 UTC, JuneParkCode commented on 42manito/src/components/Profile/Toggle.tsx
>    }, [userData, userLoading]);
그러게요....???? 이것도 제가 작업했던 부분은 아니라 냅뒀던거같은데...

2023-09-30 07:18 UTC, JuneParkCode commented on 42manito/src/components/Profile/Toggle.tsx
> +      if (!e.target.checked){
여기 e.target.checked 를 관리하는 부분을 혹시 true / false 로 명확하게 바꿔주실 수 있을까요?
이전에 제가 따로 건드리지는 않았던 부분 같은데, 다시 읽다보니 무엇이 hide 되는 상황인지 잘 읽히지 않는 것 같습니다.

마찬가지로, setIsHideMutation에서도 명확하게 true / false 로 전달해주면 나중에 읽을 때 조금 더 편리해질 것 같아요!

2023-09-30 15:09 UTC, jinaji approved these changes
변경하신 부분들 확인했습니다 
useEffect 하나가 없어도 작동에 문제 없다면 없는게 낫지 않을지 저도 조심스럽게 말해보구요 ...
true false 가 확실히 가독성에는 좋을 것 같습니다! 간단한 수정들이니 미리 승인 걸어두겠습니다 고생하셨어여~~

2023-10-01 00:35 UTC, falconlee236 commented on 42manito/src/components/Profile/Toggle.tsx
>    }, [userData, userLoading]);
그러면 이 부분은 삭제 해볼게요
작동하면서 별문제 없는지 테스트 해보겠습니당

2023-10-01 00:36 UTC, falconlee236 commented on 42manito/src/components/Profile/Toggle.tsx
> +      if (!e.target.checked){
평소 알고리즘 풀때 습관이 여기서 드러났네요
가독성부분은 혼자 코딩할때는 신경안썼는데 협업할때는 고려하는게 맞네요
명확히 true false로 바꾸겠습니다

2023-10-01 02:34 UTC, falconlee236 reviewed
수정사항 반영했습니다
한번 확인 부탁드립니다!
@JuneParkCode

2023-10-01 02:59 UTC, JuneParkCode approved these changes

2023-10-01 02:59 UTC, merged