[todo] 멘토링 취소 모달 개발
manito42/FrontEnd pull request #235
Opened 2023-10-03 08:53 UTC by falconlee236

# Summary
* 멘토링 취소 모달인 CancelModal을 추가했습니다.
* 홈 화면에 Feedback 모달을 추가했습니다.

# Description
1. 멘토링 취소 모달인 CancelModal을 추가했습니다.
해당 모달은 components/Cancel/CancelModal.tsx에 위치해 있습니다.
일단 취소 모달의 Select 항목의 내용은 기존 #190 에서 말해주셨던 항목을 참고했습니다.
해당 모달은 page/index.tsx, page/Mentorings/index.tsx, page/reservation/[reservationId].tsx에 추가했습니다.
2. 홈 화면에 Feedback 모달을 추가했습니다.
 @jinaji 님이 #230 에서 말씀하셨던 #207 이슈를 처리했습니다.

## 참고사항
취소 모달의 Select항목의 추가 아이디어가 안떠올라서 일단 3개만 했는데, 추가적으로 넣으면 좋을 것같다는 의견 있으면 남겨주세요
## ScreenShot
<img width="758" alt="image" src="https://github.com/manito42/FrontEnd/assets/52999093/2c896de6-2994-4d70-b20b-0626587c872d">
<img width="761" alt="image" src="https://github.com/manito42/FrontEnd/assets/52999093/03a3d051-88f6-43d8-b01e-92bfd739e2a5">

2023-10-03 16:45 UTC, jinaji approved these changes
홈, 멘토링 페이지, 예약 페이지에서 작동 잘 되고 메일로 사유 날아오는 것 확인했습니다!
디폴트 메세지 요정도면 된 것 같기도 하고 ... 저는 괜찮아보여용
defaultMsg.find(({value: id}) => id === value); 부분이 신기해서 한참 봤네여 ... 
오탈자 관련 코멘트 달아둔 부분 혹시 한 번 확인 가능하시면 수정 부탁드려도 될까여!! 
저에게 어사인 걸렸던 이슈 ... 해결해주셔서 감사합니다 고생하셨어여~!

2023-10-03 16:45 UTC, jinaji commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              buttonType={ButtonType.CANCLE}
이거 ... 오타가 나있었군요 🥹 혹시 괜찮으시면 원본 버튼타입부터 수정 부탁드려도 될까여!

2023-10-04 02:17 UTC, obvoso commented on 42manito/src/components/Cancel/CancelMessageSelect.tsx
> +    const msgObj = defaultMsg.find(({value: id}) => id === value);
보통 탐색을 할 때 
const msgObj = defaultMsg.find((item) => item.value === value);
이런식으로 많이 사용했는데, 사용하신 방법과 다른점이 있나여?

2023-10-04 02:33 UTC, falconlee236 commented on 42manito/src/components/Cancel/CancelMessageSelect.tsx
> +    const msgObj = defaultMsg.find(({value: id}) => id === value);
Antd에서 select는 value랑 label이라는 key값을 사용하는데 그 값이 저한테는 크게 와닿지 않아서..
Antd에서 value가 평소 id값으로 쓰이더라고요. 그걸 명확히 하고싶어서 객체 구조분해문법을 사용했었습니다

2023-10-04 05:44 UTC, falconlee236 commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              buttonType={ButtonType.CANCLE}
수정하겠습니다!!

2023-10-04 05:57 UTC, JuneParkCode requested changes
몇가지 수정사항 있습니다.

2023-10-04 05:57 UTC, JuneParkCode commented on 42manito/src/components/Cancel/CancelModal.tsx
> +      alert(msg ? msg : "Success");
sucess , error 가 아닌, 다른 메시지를 보여주세요.

2023-10-04 05:57 UTC, JuneParkCode commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              placeholder="최대 1000글자"
100자 제한입니다. API Docs 참고... 위쪽 maxLength 도 참고

2023-10-04 06:13 UTC, JuneParkCode requested changes

2023-10-04 06:13 UTC, JuneParkCode commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              onChange={(e) => setCancelMsg(e.target.value)}
지금 취소 이메일쪽으로 cancel message 가 다르게 보이고 있는데, 한번 확인 부탁드립니다. 직접 입력시에는 큰 문제 없으나, 직접 입력이 아닌 경우에 아무것도 안넘아가는 것으로 보입니다.

2023-10-04 06:13 UTC, JuneParkCode commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              onChange={(e) => setCancelMsg(e.target.value)}
제가 확인해 본 결과 처음 취소 모달이 뜰 때 cancel message 가 아무것도 없는 상태이지만, 사용자 뷰에서는 시간이 맞지 않아 취소합니다로 보입니다. 이 상태에서 제출을 할 경우 아무것도 안담긴 상태로 넘어갑니다.

한 번이라도 바꾼 경우에는 정상적으로 제출됩니다.

2023-10-04 06:16 UTC, falconlee236 commented on 42manito/src/components/Cancel/CancelModal.tsx
> +      alert(msg ? msg : "Success");
영어 말고 일단 한글로 바꾸었습니다!!

2023-10-04 06:20 UTC, JuneParkCode commented on 42manito/src/components/Cancel/CancelModal.tsx
> +      alert(msg ? msg : "Success");
다른 모달에서 처리 방식이랑 비슷하게 해주시면 됩니다. "취소가 완료되었습니다." "취소에 실패했습니다."

2023-10-04 06:24 UTC, falconlee236 commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              onChange={(e) => setCancelMsg(e.target.value)}
제가 default value를 설정했는데, 그게 useState 초기값에서는 ""로 설정되서 발생한 문제인것 같습니다
그래서 useState초기값을 해당 문자열로 만들어서 해결했습니다.

2023-10-04 06:33 UTC, JuneParkCode approved these changes

2023-10-04 06:41 UTC, merged

2023-10-04 06:44 UTC, obvoso reviewed
리뷰 달았던거 pending상태로 submit이 안되었었네여... ㅋ.ㅋ
확인 했습니다!

2023-10-04 06:44 UTC, obvoso commented on 42manito/src/components/Cancel/CancelModal.tsx
> +              buttonType={ButtonType.CANCLE}
어라 이거 머지 되면 제가 수정할게요